let stockproductos = [
    {id: 1, nombre: "BURGER SELLY OAK", descripcion: "Pan Brioche, medallon de carne de ternera, queso cheddar, panceta, cebolla frita y huevo.", precio: 1300, img: "./assets/img/sellyoak.png"},
    {id: 2, nombre: "BURGER BOURNVILLE", descripcion: "Pan Brioche, pollo rebozado tipo kentucky, rucula, cebolla morada, tomate y queso.", precio: 1200, img: "./assets/img/bournville.png"},
    {id: 3, nombre: "BURGER MOSELEY", descripcion: "Pan Brioche, medallon de soja, pepinos encurtidos, cebolla morada, tomate y queso.", precio: 1350, img: "./assets/img/moseley.png"},
    {id: 4, nombre: "BURGER EDGBASTON", descripcion: "Pan Brioche, medallon de carne de cordero, rucula, lechuga, panceta, salsa de cebolla.", precio: 1400, img: "./assets/img/edgbaston.png"},
    {id: 5, nombre: "BURGER SOLIHULL EXTRA BIG", descripcion: "Pan Brioche, molleja marinada, rucula, cebolla morada, tomate, panceta, queso y huevo.", precio: 1300, img: "./assets/img/solihull.png"},
    {id: 6, nombre: "BURGER BILLESLEY", descripcion: "Pan Brioche, bondiola de cerdo, panceta, cebolla caramelizada, tomate, queso y huevo.", precio: 1200, img: "./assets/img/billesley.png"},
    {id: 7, nombre: "PAPAS BACON XXL", descripcion: "Panceta bien crujiente, queso cheddar, un toque de perejil, con un baño de mayonesa casera.", precio: 750, img: "./assets/img/cheeseandbacon.png"},
    {id: 8, nombre: "PAPAS BEEFIE XXL", descripcion: "Papas fritas con carne frita, queso fundido, panceta crugiente, hierbas y baño de mayonesa casera.", precio: 900, img: "./assets/img/beefie.png"},
    {id: 9, nombre: "PAPAS MEXA'S XXL", descripcion: "Recuerda la gastronomía mexicana con un increíble guacamole, porotos negros, crema ácida y queso rallado.", precio: 700, img: "./assets/img/mexa.png"},
    {id: 10, nombre: "HIDROMILE ODIN x 500 ml", descripcion: "Hidromiel Odín de creación artesanal, sin conservantes artificiales, presenta un sabor diferente con el resto.", precio: 700, img: "./assets/img/hidromielodin.png"},
    {id: 11, nombre: "HIDROMIEL LOKI x 500 ml", descripcion: "Hidromiel Loki de estilo metheglin dulce, con un 7,5% de volumen alcohólico y espuma de color rosado.", precio: 700, img: "./assets/img/hidromielloki.png"},
    {id: 12, nombre: "CERVEZA QUILMES", descripcion: "Es la más emblemática de la cervecería y las más representativa de Argentina alrededor del mundo.", precio: 500, img: "./assets/img/cervezaquilmes.png"},
    {id: 13, nombre: "GASEOSA COCA COLA x 500 ml", descripcion: "Coca-Cola es una bebida gaseosa vendida a nivel mundial, en más de doscientos países del mundo.", precio: 500, img: "./assets/img/coca.png"},
    {id: 14, nombre: "GASEOSA SPRITE x 500 ml", descripcion: "Sprite refrescante, transparente y burbugeante con sabor a Lima o limón, incolora y sin cafeína.", precio: 500, img: "./assets/img/sprite.png"},
    {id: 15, nombre: "GASEOSA FANTA x 500 ml", descripcion: "Fanta refrescante y burbugeante con sabor a frutas naturales seleccionadas y sin cafeina.", precio: 500, img: "./assets/img/fanta.png"},
    {id: 16, nombre: "AGUA TONICA x 500 ml", descripcion: "Santa Quina  elaborada a partir de componentes naturales. Con una burbuja fina e integrada..", precio: 500, img: "./assets/img/tonica.png"},
]
